/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id:"sr284c-q8oY",
    categoryName:"Solo Travel",
    title:"My Solo Trip to ALASKA | Cruising From Vancouver to Anchorage",
    views: 1809861,
    dateAdded:"July 18, 2019",
    creator:"Allison Anderson",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-iYz91vI4tMMJ-ust5CwnqhletoSZxGA-cwl6Pag=s176-c-k-c0x00ffffff-no-rj",
    description:"I spent 11 days cruising up the coast of Alaska and it was MAGICAL.",
  },
  {
    _id:"CNdTBvbONis",
    categoryName:"Adventure Travel",
    title:"I Did Bungee Jumping, FlyBoarding & Fly Dining In Goa | Curly Tales",
    views:11000,
    dateAdded:"June 8, 2022",
    creator:"Curly Tales",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
    description:"Goa is not just for beaches & booze, Curly Tales adventure enthusiast, Bianca Saurastri showcase some of the offbeat adventure activities apart from the water sports that you can try when you go to goa. From FlyBoarding, Fly Dining to Bungee Jumping we have done it all. We started off with FlyBoarding which was exciting yet very challenging, moving on to Bungee Jumping where we jumped from a height of 55m & then ended our evening with Fly Dining in the sky, enjoying a 3-course meal. Watch the whole video & let us know who you would like to do these activities with. "

  },
  {
    _id:"RFsXzl3LXP4",
    categoryName:"Luxury Travel",
    title:"What It’s Like Ep 1: Cruise Vacation In India | Cordelia Cruises - Mum To Lakshadweep | Curly Tales",
    views:1887155,
    dateAdded:"December 31, 2021",
    creator:"Curly Tales",
    description:"I went on a 5-night cruise vacation to Lakshadweep and Goa with my entire family & had one of a kind experience with Cordelia Cruises. With exquisite dining, non-stop Entertainment, endless ocean views and luxury accommodations, you can sail to a beautiful holiday too, just like us! Cordelia Cruises is India’s premium cruise liner and aspires to promote and drive the cruise culture in India. You will sail on The Empress which is an iconic vessel which first set sail in the year 1990 with the name The Nordic Empress. After sailing the Bahamas and the Caribbean, The Empress is now cruising the West and the East coast of India.",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",

  },
  {
    _id:"wZEmHJ3nj5c", 
    categoryName:"Adventure Travel",
    views:"4442105",
    dateAdded:" June 24, 2019",
    title:"EVEREST - The mountain that changed my life | Documentary Summit |",
    creator:"ImadClicks",
    logo:"https://yt3.ggpht.com/HmeddO1aem_POqXXi-QVEWSKnPm2HAK3ubQCpVT03uuc3MdPB6z_yPZv39WGlQWk75kz9_AUOQ=s176-c-k-c0x00ffffff-no-rj",
    description:"A documentary based on the Youngest mountaineer of Kashmir to reach EVEREST. How he had to abandon his dream when he was just few hundred meters away from conquering it SUMMIT 2019 ",
  },
  {
    _id:"GhXrEgq3ubM",
    categoryName:"Road Trip",
    views:311509,
    dateAdded:"June 20, 2021",
    creator:"Monkey Magic",
    title:"My Dream RoadTrip across LADAKH (my fav fav trip) | Monkey Magic",
    logo:"https://yt3.ggpht.com/C2kOdIb0AP6DQBmMBYNLZrNBoAcD2Sy7vyk1nl7JKdDdD-YmjmUdh8144qv3cBM-dE-DzIUQNA=s176-c-k-c0x00ffffff-no-rj",
    description:"Doston, It was my dream to go on road trip to Ladakh and finally It happened in 2021. I covered 6 famous places  (Hanle Tso moriri Chumathang Ulley Leh) in 6 days. And best part about this Ladakh Road trip is Snow Leopard ",
  },
  {
    _id:"HfX4a3Iom0g",
    views:14561,
    categoryName:"Group Travel",
    dateAdded:"August 22, 2022",
    title:"Post Grad Trip Episode 7: WE WENT TO THE BEST CLUB IN THE WORLD! (BALI VLOG)",
    creator:"Jayraj Gill",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu86VIwRJmFytrNdo8GdGX3--772Y4Y_NFXyPy-b=s176-c-k-c0x00ffffff-no-rj",
    description:"It's a post grad trip to Bali."
  },
  {

    _id:"sOHZzL-gYtw",
    categoryName:"Solo Travel",
    views:2243056,
    dateAdded:"October 5, 2020",
    title:"SOLO RIDE || MUMBAI TO KEDARNATH || Ridergirl Vishakha | Day 1",
    creator:"RiderGirl Vishakha",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu99Vk-OHgBUhaP69DsT4cA3e-zsFsrpAPrNaVJHEVo=s176-c-k-c0x00ffffff-no-rj",
    description:" HAR HAR MAHADEV! Here's Day 1 of my Dream Ride { 10 places to visit on my bike before I Die}. KEDARNATH - There is some Magic in the name itself, after a lot of struggle I managed to start my ride with my Mumbai Riding Solo.... In this vlog, I reach Vadodara - Gujrat!. I hope you all would enjoy this vlog, also let's stay together in This DIVINE DESTINATION RIDE! JAI BHOLE NATH KI - CHINTA KIS BAAT KI?"
  },
  {
    _id:"-lwBKCYDxiY",
    categoryName:"Road Trip",
    views:77859,
    dateAdded:"August 28, 2021",
    title:"Summertime in Leh | Leh Ladakh in New Thar 2021 l Travel Vlog | Couple Vlogs",
    creator:"Tapchi",
    logo:"https://yt3.ggpht.com/Msmjrq7GHyYWwR3TkQORWaHPJMv06DRpo29BCBwGL2-Gdah7Mtu3zByPTIY7Hdvk9NmXrNx-SQ=s176-c-k-c0x00ffffff-no-rj",
    description:"The big day is here! We finally arrive in Leh after a long but such a beautiful drive! We meet a cutie pie dog, eat a lot of Maggie, see a lot of mountains, fly the drone to get some majestic shots. "

  },
  {
    _id: "PKLP-2eP0LM",
    categoryName:"Group Travel",
    views: 919833,
    dateAdded:"March 5, 2020",
    title: "MOROCCO | A 9 Day Group Tour | Ep1: Marrakesh to the Sahara",
    creator:"Karl Watson: Travel Documentaries",
    description:"This was my first time in the country and is documented in a new 2 part travel documentary series. ",
    logo:"https://yt3.ggpht.com/4B2ZSGdFyERg534Bygy-VHpkd2IjyHyTLqVpfZ0QD0CRJN8joHHNXU5tuZhCM4Iyu1B6F-pN=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"7mySE3sfYsk",
    categoryName:"Group Travel",
    views:56408,
    title:"TRIP TO UTTARAKHAND - Rishikesh, Joshimath, Auli, Mussorie - with my friends | PART 1 | Navika Kotia",
    dateAdded:"February 16, 2022",
    creator:"Navika and Shivansh",
    logo:"https://yt3.ggpht.com/EajHKBqhcfpb0fwyHyz_Fx1QkbOJV1XRjFkFUjSjvkGnlLALoz0TY7yIaI4L9XC38hO0DIFm5w=s176-c-k-c0x00ffffff-no-rj",
    description:"Hey everyone, I took a trip to Uttarakhand with my friends during this winter season! We went from Mumbai to Rishikesh to Joshimath and Auli and then Mussoorie. ",
  },
  {
    _id:"EjgJln9j6Y4",
    categoryName: "Group Travel",
    views:46486,
    dateAdded: "January 7, 2021",
    title:"Nainital Group Tour | Nainital Trip | My First Group Tour to Nainital | Nainital Uttarakhand",
    creator:"Distance Between",
    description:"This video belongs to my Nainital Group Tour.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLQHDJQmV9lSr9msTq_265jUfyQWiia7FwjkJlP2LA=s176-c-k-c0x00ffffff-no-rj",

  },
  {
    _id:"XncoZAkq_Qs",
    categoryName:"Solo Travel",
    views: 518759,
    dateAdded: "April 24, 2018",
    title:"Solo Girl In Bali, Indonesia! Bali vlog #1",
    creator:"Tanya Khanijow",
    description:"Bali was an out of the world experience and you have to watch this video till the end to know why (For an early sneak peek).",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",

  },
  
  
  {
    _id:"JJnPnni_jmE",
    categoryName:"Adventure Travel",
    views:414324,
    dateAdded:"February 15, 2021",
    title:"You Won't Believe this is India! Surfing for beginners in Mulki, Karnataka",
    creator:"Tanya Khanijow",
    description:"This is the Surfing for beginners edition! Also, I aim to try these activities in India, because did you know that you don’t always have to travel abroad or spend insane amounts of money to fulfill all your wishes :)",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"jB2Z9PA7iKI",
    categoryName:"Luxury Travel",
    views:8127434,
    title:"Dubai. Luxury life tour. Big Episode.",
    creator:"Anton somewhere",
    dateAdded:"January 15, 2019",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu_Nb75ncNqSe-SCEDBnyTry4lnatUYmyBYIefbNHg=s176-c-k-c0x00ffffff-no-rj",
    description:"This Big Episode is dedicated to Dubai and a luxury side of it's life - private islands, villas for 200000000$ and other rich things. We also will tell you about new and interesting things launched in this city for the last couple of years and of course some exclusive stories",

  },
  {
    _id:"xfvQN-T2OiY",
    categoryName:"Luxury Travel",
    views:635010,
    dateAdded:"February 5, 2022",
    title:"The Gstaad Palace Hotel (Switzerland) | An ultra-luxe winter getaway (full tour)",
    creator:"the Luxury Travel Expert",
    description:" Join me on a full tour of Gstaad Palace, one of the best 5-star hotels in the Swiss Alps.",
    logo:"https://yt3.ggpht.com/8pTWfgrXfrGin2LbwiuSARil48hGkyml2P2a-bRFCrWodkiA3sfnSjGl0aa2uFhXxGtSgazmEW0=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"NJ_UupUgAzg",
    categoryName:"Road Trip",
    views:759964,
    dateAdded:"October 27, 2020",
    title:"Mumbai To Goa Road Trip | Curly Tales",
    creator:"Curly Tales",
    description:"I have documented the entire journey as I pass through Pune, Satara, Kolhapur, Sindudurg and finally Goa.",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"OpaGQRv49r0",
    categoryName:"Road Trip",
    views:168420,
    dateAdded:"Dec 4, 2019",
    title:"Travel Tales Ep 7- Road Trip From India To Thailand | Curly Tales",
    creator:"Curly Tales ",
    description:"If you're looking to take a road trip through cross country borders then Mr. Ajay Yadav shares his insights & knowledge as to how you can make it possible.  ",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"uDlz01lFHPk",
    categoryName:"Road Trip",
    views:7706219,
    dateAdded:"Feb 27, 2019",
    title:"WDA|| Bangalore to London on Bike || India To UK || 21 countries || 23500km || World Ride",
    creator:"White Dragon Adventures",
    description:"Bangalore to London 76 days 21 countries 23500kms 2 Continents. Manjunatha C and King Richard the Duo started dream Ride Bangalore to London on 16th April 2018 from Townhall blore, travel Bhutan, Myamnar, Thailand, Loas, China, Kyrgyzstan, Uzbekistan, Kazakhstan, Russia, Estonia, Latvia, Lithuania,  Poland, Czech Republic, Austria, Italy, Switzerland, France, Bulgaria, Netherland, France Calais, thru English channel train to UK London.",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-ukQacSdmX5vo80xvLPnqsSp1FiKpbzRijGRjh7Q=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"VToPBUA0Hv8",
    categoryName:"Solo Travel",
    views:190577,
    dateAdded:"Jul 6, 2020",
    title:"SOLO WORLD RIDE AMERICA TO INDIA - BANGALORE",
    creator:"White Dragon Adventures",
    description:"THE INCREDIBLE SOLO WORLD RIDE // SOLO MOTORCYCLE WORLD RIDE FROM INDIA// WORLD RIDE COVERING 5 CONTINENTS 37 COUNTRIES //ASIA, EUROPE, NORTH AMERICA, SOUTH AMERICA, AUSTRALIA- A dream journey started by a duo, halted by circumstances but continued to a mind boggling solo ride.",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-ukQacSdmX5vo80xvLPnqsSp1FiKpbzRijGRjh7Q=s176-c-k-c0x00ffffff-no-rj",

  },
  
  {
    _id:"5Vc9wQIOkew",
    categoryName:"Luxury Travel",
    views:5816692,
    dateAdded:"December 24, 2019",
    title:"1 Night at the Taj Hotel | Mumbai's Legendary Luxury Hotel!",
    creator:"Jessica Savano",
    description:"Ever wonder what it was like to stay at the legendary Taj Mahal Palace in Mumbai, India? Come along on this amazing adventure with me as I live it up in luxury...just for a night!",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-DhM0rLN9Y1fS4OdvwnHbRTBnL6gWPO2pj02viS4M=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"FJBdLsUeSw0",
    categoryName:"Adventure Travel",
    views:93881,
    dateAdded:"October 15, 2020",
    title:"Top 12 Adventure Destinations In India For Those Who Like The Thrill | Curly Tales",
    creator:"Curly Tales",
    description:"Life becomes much happier and worth living when we treat our souls with adventurous trips, right? And there are innumerable thrilling sports that bring out that adrenaline rush in all of us, be it Hiking, Paragliding, Mountain Biking, River Rafting or SkyDiving. But do you really know all the places in India which offer the best of adventure activities? Don't worry, we're telling you about the top 12 adventure destinations in India that have some crazy activities in store for you!",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
    
  },
  {
    _id:"iZgVwbdNKqY",
    categoryName:"Solo Travel",
    views: 295780,
    dateAdded:"Apr 6, 2019",
    title:"Solo Trip to Bhutan by Road | Phuntsholing | How to get a permit for Indians? | Bhutan Series Intro",
    creator:"Tanya Khanijow",
    description:"HELLO MY PEOPLE.  I'm visiting Bhutan solo by road, and this is the first video in the series. The nearest airport is Bagdogra airport although you can also fly Druk Airways and land directly at Paro (expensive option). From Bagdogra it takes about 5 hours to reach Phuntsholing by road and you can get a taxi from right outside the airport. At Phuntsholing border you will require a permit to visit beyond the 5 km border radius.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",
  },


  {
    _id:"sBPz8wH5AGs",
    categoryName:"Budget Travel",
    views:105368,
    dateAdded:"July 8, 2018",
    title:"Paris For Rs. 30,000 - Hostel, Parties, Indian Food, Sim, Museums, Boats, Palaces- Indian Vlogger",
    creator:"Traveling Desi",
    description:"Rs. 30,000 for a 6 day trip to the beautiful city of Paris.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLSXDQT_t4cYk0Fp2RQqqYsw-fl-Vyq-nXtaAcKb=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"KOC7MZBlcEg",
    categoryName:"Budget Travel",
    views: 65081,
    dateAdded: "October 25, 2021",
    title: "Rishikesh Budget Trip Under 5000/- For 4-5 Days Where to stay, Food, Train/Bus (Full Information)",
    creator: "Wanderlust हिमानी ",
    description: "Hey Wanders,Here in today's budget traveling video I am sharing the most requested one because solo travelers first choice is Rishikesh and I've been there quite many times so thought to make this one for you, You guys can travel to Rishikesh for good 4-5 days with all including 5000 INR yes you can watch this video till the end.",
    logo: "https://yt3.ggpht.com/yd5Vf8Y6UpYDm-a0Lh8fdcdDJI_XEcB_NAb5zznZH2utPOLRN8YTDafWQRyUM7tTn2dKOdbOfQ=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"LyGdh48ryAw",
    categoryName:"Budget Travel",
    views:205141,
    dateAdded:"June 4, 2022",
    title:"Mussoorie Tour Plan & BUDGET | A-Z Mussoorie Trip Guide | Mussoorie Tourist Places",
    creator:"Kunal K Vlogs",
    description:"Mussoorie Tour Total Budget & Plan with COMPLETE Travel Guide. Hey My Family ❤️, This is MY Mussoorie Tour 😃, Hope you will enjoy a lot. In this video You will know about Mussoorie Tour Plan & Cheapest Budget Itinerary for You❤️ ( Mussoorie Kaise Pahuche ). You'll know more about, Best Travel Options for Mussoorie, Mussoorie Hotel Expenses & Best Hotel Location with Mountain View, Mussoorie Food expenses (Veg/non Veg), Mussoorie Conveyance Charges (Taxi, Scooty, Car), Mussoorie Complete Tour Plan & Total Budget, Mussoorie Tourist Places In summer",
    logo:"https://yt3.ggpht.com/dm-0sbnqj-KeN6ogEXkzHbFjFUBd5absHPBHOv__aszbCF8DG5X0n-cvKYyLPOaDiRK8swopmQ=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"vms9vYzDE6M",
    categoryName: "Budget Travel",
    views:267704,
    dateAdded:"May 6, 2022",
    title:"Kashmir Tour Cost & Itinerary | Taxi Charges, Activities, Scams | Must Watch!! Detailed Travel Guide",
    creator: "Pulak and Sangeeta",
    description:"In this video, we have shared detailed information about the Kashmir tour about talked about all the expenses like Taxi Charges, Activities, Scams and everything you need to know before planning a trip to Kashmir. After watching the video, most of your queries about the Kashmir travel plan will be resolved and if you like this informative video, please share it with your friends and family.",
    logo:"https://yt3.ggpht.com/Jokfph5YccTl9hcJSGD3R_Y6Jd3Mj40OccCnPvgL4pZ2saCwUUrMK5g6IHvz6fr3fljEq_HCeg=s176-c-k-c0x00ffffff-no-rj",
  }
];
