/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "PKLP-2eP0LM",
    categoryName:"Group Travel",
    views: 919833,
    dateAdded:"March 5, 2020",
    title: "MOROCCO | A 9 Day Group Tour | Ep1: Marrakesh to the Sahara",
    creator:"Karl Watson: Travel Documentaries",
    description:"This was my first time in the country and is documented in a new 2 part travel documentary series. ",
    logo:"https://yt3.ggpht.com/4B2ZSGdFyERg534Bygy-VHpkd2IjyHyTLqVpfZ0QD0CRJN8joHHNXU5tuZhCM4Iyu1B6F-pN=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"EjgJln9j6Y4",
    categoryName: "Group Travel",
    views:46486,
    dateAdded: "January 7, 2021",
    title:"Nainital Group Tour | Nainital Trip | My First Group Tour to Nainital | Nainital Uttarakhand",
    creator:"Distance Between",
    description:"This video belongs to my Nainital Group Tour.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLQHDJQmV9lSr9msTq_265jUfyQWiia7FwjkJlP2LA=s176-c-k-c0x00ffffff-no-rj",

  },
  {
    _id:"XncoZAkq_Qs",
    categoryName:"Solo Travel",
    views: 518759,
    dateAdded: "April 24, 2018",
    title:"Solo Girl In Bali, Indonesia! Bali vlog #1",
    creator:"Tanya Khanijow",
    description:"Bali was an out of the world experience and you have to watch this video till the end to know why (For an early sneak peek).",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",

  },
  {
    _id:"JJnPnni_jmE",
    categoryName:"Adventure",
    views:414324,
    dateAdded:"February 15, 2021",
    title:"You Won't Believe this is India! Surfing for beginners in Mulki, Karnataka",
    creator:"Tanya Khanijow",
    description:"This is the Surfing for beginners edition! Also, I aim to try these activities in India, because did you know that you don’t always have to travel abroad or spend insane amounts of money to fulfill all your wishes :)",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"xfvQN-T2OiY",
    categoryName:"Luxury Travel",
    views:635010,
    dateAdded:"February 5, 2022",
    title:"The Gstaad Palace Hotel (Switzerland) | An ultra-luxe winter getaway (full tour)",
    creator:"the Luxury Travel Expert",
    description:" Join me on a full tour of Gstaad Palace, one of the best 5-star hotels in the Swiss Alps.",
    logo:"https://yt3.ggpht.com/8pTWfgrXfrGin2LbwiuSARil48hGkyml2P2a-bRFCrWodkiA3sfnSjGl0aa2uFhXxGtSgazmEW0=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"NJ_UupUgAzg",
    categoryName:"Road trip",
    views:759964,
    dateAdded:"October 27, 2020",
    title:"Mumbai To Goa Road Trip | Curly Tales",
    creator:"Curly Tales",
    description:"I have documented the entire journey as I pass through Pune, Satara, Kolhapur, Sindudurg and finally Goa.",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"OpaGQRv49r0",
    categoryName:"Road Trip",
    views:168420,
    dateAdded:"Dec 4, 2019",
    title:"Travel Tales Ep 7- Road Trip From India To Thailand | Curly Tales",
    creator:"Curly Tales ",
    description:"If you're looking to take a road trip through cross country borders then Mr. Ajay Yadav shares his insights & knowledge as to how you can make it possible.  ",
    logo:"https://yt3.ggpht.com/zdU2A41m8coX5YUdqKM1Wb9fQYAwpX_u3qOErZlSEx-u0Rnw3-CnB_dSxtRJ3LCkGihs6fBe=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"uDlz01lFHPk",
    categoryName:"Road Trip",
    views:7706219,
    dateAdded:"Feb 27, 2019",
    title:"WDA|| Bangalore to London on Bike || India To UK || 21 countries || 23500km || World Ride",
    creator:"White Dragon Adventures",
    description:"Bangalore to London 76 days 21 countries 23500kms 2 Continents. Manjunatha C and King Richard the Duo started dream Ride Bangalore to London on 16th April 2018 from Townhall blore, travel Bhutan, Myamnar, Thailand, Loas, China, Kyrgyzstan, Uzbekistan, Kazakhstan, Russia, Estonia, Latvia, Lithuania,  Poland, Czech Republic, Austria, Italy, Switzerland, France, Bulgaria, Netherland, France Calais, thru English channel train to UK London.",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-ukQacSdmX5vo80xvLPnqsSp1FiKpbzRijGRjh7Q=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    _id:"VToPBUA0Hv8",
    categoryName:"Solo Travel",
    views:190577,
    dateAdded:"Jul 6, 2020",
    title:"SOLO WORLD RIDE AMERICA TO INDIA - BANGALORE",
    creator:"White Dragon Adventures",
    description:"THE INCREDIBLE SOLO WORLD RIDE // SOLO MOTORCYCLE WORLD RIDE FROM INDIA// WORLD RIDE COVERING 5 CONTINENTS 37 COUNTRIES //ASIA, EUROPE, NORTH AMERICA, SOUTH AMERICA, AUSTRALIA- A dream journey started by a duo, halted by circumstances but continued to a mind boggling solo ride.",
    logo:"https://yt3.ggpht.com/ytc/AMLnZu-ukQacSdmX5vo80xvLPnqsSp1FiKpbzRijGRjh7Q=s176-c-k-c0x00ffffff-no-rj",

  },
  {
    _id:"iZgVwbdNKqY",
    categoryName:"Solo Travel",
    views: 295780,
    dateAdded:"Apr 6, 2019",
    title:"Solo Trip to Bhutan by Road | Phuntsholing | How to get a permit for Indians? | Bhutan Series Intro",
    creator:"Tanya Khanijow",
    description:"HELLO MY PEOPLE.  I'm visiting Bhutan solo by road, and this is the first video in the series. The nearest airport is Bagdogra airport although you can also fly Druk Airways and land directly at Paro (expensive option). From Bagdogra it takes about 5 hours to reach Phuntsholing by road and you can get a taxi from right outside the airport. At Phuntsholing border you will require a permit to visit beyond the 5 km border radius.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLRhGnCw_rLZ8kNI4kIyQQqY44wIYnHMKsum2ITsRCw=s176-c-k-c0x00ffffff-no-rj",
  },


  {
    _id:"sBPz8wH5AGs",
    categoryName:"Budget travel",
    views:105368,
    dateAdded:"July 8, 2018",
    title:"Paris For Rs. 30,000 - Hostel, Parties, Indian Food, Sim, Museums, Boats, Palaces- Indian Vlogger",
    creator:"Traveling Desi",
    description:"Rs. 30,000 for a 6 day trip to the beautiful city of Paris.",
    logo:"https://yt3.ggpht.com/ytc/AKedOLSXDQT_t4cYk0Fp2RQqqYsw-fl-Vyq-nXtaAcKb=s176-c-k-c0x00ffffff-no-rj",
  },
];
